### ISSUE TITLE
Deleting conditions in dashboard

### ISSUE THREAD

**Issue by amurphy-cl** [CarnegieLearningWeb/educational-experiment-service#108]
When going back to edit an experiment, the list of Conditions automatically rearranges the order of Conditions and also only allows removal of the last two Conditions. We should be able to remove any Condition

**Comment by ppratikcr7** [comment]
@amurphy-cl fix is merged, now you can verify.

**Comment by amurphy-cl** [comment]
Reopening because I noticed that when there are only 2 conditions, you still can't delete one of them.

**Comment by ppratikcr7** [comment]
The functionality is such that we need to have atleast two conditions, so we disable the option to further delete conditions.

**Comment by SritterCL** [comment]
Although it's weird to have an experiment with only one condition, I don't see why we wouldn't support it. At the least, it sometimes makes it easier to change an experiment by deleting one condition and then adding a new one (rather than editing one).

**Comment by ppratikcr7** [comment]
@SritterCL So you want that we should allow the user to delete up to zero conditions and then they can create new conditions and we only let them move ahead when they have two conditions, right? If yes, we will make the changes accordingly.

**Comment by SritterCL** [comment]
Right. It's OK in the UI to delete conditions so that there's only 1 (or zero). But you can't change the status out of "inactive" unless you have at least 2 conditions.

@nirmalpatel - as an aside, I think an experiment with 1 condition (and some whitelist/blacklist of users) is feature flagging. I wouldn't do this at the user level but the implementation seems pretty close. I'm not sure where feature flagging (as a feature) stands at this point. (would it ever make sense to do random assignment within feature flagging?)

**Comment by nirmalpatel** [comment]
@SritterCL I think feature flags are probably more useful for canary testing where we want to see whether releasing a feature breaks the system or not (this would need segmentation for sure as people might want to release features to a much smaller population)... Or maybe another use case is to release a specific new functionality to a certain user segment. I guess experiments are more about is my new feature as good as the old one and feature flags are more about whether my feature works in production well or not...
